# 工作流的名称，会显示在 GitHub Actions 页面
name: Sitemap Checker

# 触发工作流程的事件
on:
  # 1. 定时触发：使用 CRON 表达式
  #    这里的 '0 16 * * *' 代表在 UTC 时间每天下午 4 点执行。
  #    这对应的是中国/北京时间 (UTC+8) 的午夜 0 点。
  schedule:
    - cron: '0 16 * * *'
  
  # 2. 手动触发：允许您在 GitHub Actions 页面手动点击按钮来运行此工作流程
  workflow_dispatch:

# 定义工作任务
jobs:
  check-sitemap:
    # 指定任务运行的虚拟环境，这里使用最新的 Ubuntu 系统
    runs-on: ubuntu-latest

    # 定义任务执行的步骤
    steps:
      # 步骤 1: 检出代码
      - name: Check out repository
        uses: actions/checkout@v4

      # 步骤 2: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 步骤 3: 安装依赖库
      # 【重要改动】在这里增加了 lxml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      # 步骤 4: 运行 Python 脚本
      - name: Run sitemap checker script
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: python sitemap_checker.py

      # 步骤 5: 提交并推送文件变更
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add urls.txt new_urls.txt
          if ! git diff --staged --quiet; then
            git commit -m "chore: 自动更新 sitemap URL 列表"
            git push
          else
            echo "文件无变化，无需提交。"
          fi
